C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'tistory_golden.py': [Errno 2] No such file or directory
C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'tistory_golden.py': [Errno 2] No such file or directory
C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'tistory_golden.py': [Errno 2] No such file or directory
C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'tistory_golden.py': [Errno 2] No such file or directory
C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'C:\Users\mypak\PycharmProjects\PythonProject1\tistory_golden.py': [Errno 2] No such file or directory
C:\Users\mypak\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'C:\Users\mypak\PycharmProjects\PythonProject1\tistory_golden.py': [Errno 2] No such file or directory
